language: r
cache: packages

r_packages:
- data.table
- ggplot2
- rsvg
- grImport2
- ggpubr
- RColorBrewer
- gifski
- av

bioc_packages:
- IRanges
- DOSE
- org.Mm.eg.db
- org.Hs.eg.db
- org.Rn.eg.db
- org.Dr.eg.db
- org.Sc.sgd.db
- clusterProfiler

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - libnlopt-dev
      - libavfilter-dev

notifications:
    email:
    on_success: never
on_failure: never

warnings_are_errors: false
