language: r
cache: packages

r_packages:
- data.table
- ggplot2
- magick
- rsvg
- grImport2
- ggpubr
- RColorBrewer

bioc_packages:
- IRanges
- org.Mm.eg.db
- clusterProfiler
- multtest
- DOSE

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - libnlopt-dev

notifications:
    email:
    on_success: never
on_failure: never

warnings_are_errors: false
