# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    


jobs:      
  envsetting1:
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: $HOME/ffmpeg_build/lib/pkgconfig
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         r-version: ['4.0.3']
         os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg            
          
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck
      - uses: r-lib/actions/check-r-package@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Query dependencies
        run: |
          install.packages(c('remotes', 'BiocManager'), INSTALL_opts="--no-multiarch")
          options(repos = c(getOption("repos"), BiocManager::repositories()))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck","pandoc"), 
          INSTALL_opts="--no-multiarch")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

